// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AccountHandle : RemoteTableHandle<EventContext, Account>
        {
            protected override string RemoteTableName => "account";

            public sealed class AccountIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Account row) => row.AccountId;

                public AccountIdUniqueIndex(AccountHandle table) : base(table) { }
            }

            public readonly AccountIdUniqueIndex AccountId;

            public sealed class UsernameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Account row) => row.Username;

                public UsernameUniqueIndex(AccountHandle table) : base(table) { }
            }

            public readonly UsernameUniqueIndex Username;

            internal AccountHandle(DbConnection conn) : base(conn)
            {
                AccountId = new(this);
                Username = new(this);
            }

            protected override object GetPrimaryKey(Account row) => row.Username;
        }

        public readonly AccountHandle Account;
    }
}
