// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CharacterHandle : RemoteTableHandle<EventContext, Character>
        {
            protected override string RemoteTableName => "character";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Character row) => row.EntityId;

                public EntityIdUniqueIndex(CharacterHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class PlayerIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(Character row) => row.PlayerId;

                public PlayerIdIndex(CharacterHandle table) : base(table) { }
            }

            public readonly PlayerIdIndex PlayerId;

            internal CharacterHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(Character row) => row.EntityId;
        }

        public readonly CharacterHandle Character;
    }
}
