// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EntityCharacterHandle : RemoteTableHandle<EventContext, EntityCharacter>
        {
            protected override string RemoteTableName => "entity_character";

            public sealed class CharacterIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(EntityCharacter row) => row.CharacterId;

                public CharacterIdIndex(EntityCharacterHandle table) : base(table) { }
            }

            public readonly CharacterIdIndex CharacterId;

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(EntityCharacter row) => row.EntityId;

                public EntityIdUniqueIndex(EntityCharacterHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal EntityCharacterHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(EntityCharacter row) => row.EntityId;
        }

        public readonly EntityCharacterHandle EntityCharacter;
    }
}
