// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SessionHandle : RemoteTableHandle<EventContext, Session>
        {
            protected override string RemoteTableName => "session";

            public sealed class AccountIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Session row) => row.AccountId;

                public AccountIdUniqueIndex(SessionHandle table) : base(table) { }
            }

            public readonly AccountIdUniqueIndex AccountId;

            public sealed class CharacterIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(Session row) => row.CharacterId;

                public CharacterIdIndex(SessionHandle table) : base(table) { }
            }

            public readonly CharacterIdIndex CharacterId;

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Session row) => row.Identity;

                public IdentityUniqueIndex(SessionHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal SessionHandle(DbConnection conn) : base(conn)
            {
                AccountId = new(this);
                CharacterId = new(this);
                Identity = new(this);
            }

            protected override object GetPrimaryKey(Session row) => row.Identity;
        }

        public readonly SessionHandle Session;
    }
}
