// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateEntityHandler(ReducerEventContext ctx, string entityType);
        public event CreateEntityHandler? OnCreateEntity;

        public void CreateEntity(string entityType)
        {
            conn.InternalCallReducer(new Reducer.CreateEntity(entityType), this.SetCallReducerFlags.CreateEntityFlags);
        }

        public bool InvokeCreateEntity(ReducerEventContext ctx, Reducer.CreateEntity args)
        {
            if (OnCreateEntity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateEntity(
                ctx,
                args.EntityType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateEntity : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_type")]
            public string EntityType;

            public CreateEntity(string EntityType)
            {
                this.EntityType = EntityType;
            }

            public CreateEntity()
            {
                this.EntityType = "";
            }

            string IReducerArgs.ReducerName => "CreateEntity";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateEntityFlags;
        public void CreateEntity(CallReducerFlags flags) => CreateEntityFlags = flags;
    }
}
