// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateCharacterHandler(ReducerEventContext ctx, string name, string race);
        public event CreateCharacterHandler? OnCreateCharacter;

        public void CreateCharacter(string name, string race)
        {
            conn.InternalCallReducer(new Reducer.CreateCharacter(name, race), this.SetCallReducerFlags.CreateCharacterFlags);
        }

        public bool InvokeCreateCharacter(ReducerEventContext ctx, Reducer.CreateCharacter args)
        {
            if (OnCreateCharacter == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateCharacter(
                ctx,
                args.Name,
                args.Race
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateCharacter : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "race")]
            public string Race;

            public CreateCharacter(
                string Name,
                string Race
            )
            {
                this.Name = Name;
                this.Race = Race;
            }

            public CreateCharacter()
            {
                this.Name = "";
                this.Race = "";
            }

            string IReducerArgs.ReducerName => "CreateCharacter";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateCharacterFlags;
        public void CreateCharacter(CallReducerFlags flags) => CreateCharacterFlags = flags;
    }
}
