// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteCharacterHandler(ReducerEventContext ctx, uint characterId);
        public event DeleteCharacterHandler? OnDeleteCharacter;

        public void DeleteCharacter(uint characterId)
        {
            conn.InternalCallReducer(new Reducer.DeleteCharacter(characterId), this.SetCallReducerFlags.DeleteCharacterFlags);
        }

        public bool InvokeDeleteCharacter(ReducerEventContext ctx, Reducer.DeleteCharacter args)
        {
            if (OnDeleteCharacter == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteCharacter(
                ctx,
                args.CharacterId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteCharacter : Reducer, IReducerArgs
        {
            [DataMember(Name = "character_id")]
            public uint CharacterId;

            public DeleteCharacter(uint CharacterId)
            {
                this.CharacterId = CharacterId;
            }

            public DeleteCharacter()
            {
            }

            string IReducerArgs.ReducerName => "DeleteCharacter";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteCharacterFlags;
        public void DeleteCharacter(CallReducerFlags flags) => DeleteCharacterFlags = flags;
    }
}
