// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LoginHandler(ReducerEventContext ctx, string username, string passwordHash);
        public event LoginHandler? OnLogin;

        public void Login(string username, string passwordHash)
        {
            conn.InternalCallReducer(new Reducer.Login(username, passwordHash), this.SetCallReducerFlags.LoginFlags);
        }

        public bool InvokeLogin(ReducerEventContext ctx, Reducer.Login args)
        {
            if (OnLogin == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLogin(
                ctx,
                args.Username,
                args.PasswordHash
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Login : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "password_hash")]
            public string PasswordHash;

            public Login(
                string Username,
                string PasswordHash
            )
            {
                this.Username = Username;
                this.PasswordHash = PasswordHash;
            }

            public Login()
            {
                this.Username = "";
                this.PasswordHash = "";
            }

            string IReducerArgs.ReducerName => "Login";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags LoginFlags;
        public void Login(CallReducerFlags flags) => LoginFlags = flags;
    }
}
