// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Account
    {
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "password_hash")]
        public string PasswordHash;
        [DataMember(Name = "account_id")]
        public uint AccountId;
        [DataMember(Name = "created_at")]
        public ulong CreatedAt;
        [DataMember(Name = "number_of_characters")]
        public uint NumberOfCharacters;

        public Account(
            string Username,
            string PasswordHash,
            uint AccountId,
            ulong CreatedAt,
            uint NumberOfCharacters
        )
        {
            this.Username = Username;
            this.PasswordHash = PasswordHash;
            this.AccountId = AccountId;
            this.CreatedAt = CreatedAt;
            this.NumberOfCharacters = NumberOfCharacters;
        }

        public Account()
        {
            this.Username = "";
            this.PasswordHash = "";
        }
    }
}
