// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Character
    {
        [DataMember(Name = "entity_id")]
        public uint EntityId;
        [DataMember(Name = "player_id")]
        public uint PlayerId;
        [DataMember(Name = "direction")]
        public DbVector2 Direction;

        public Character(
            uint EntityId,
            uint PlayerId,
            DbVector2 Direction
        )
        {
            this.EntityId = EntityId;
            this.PlayerId = PlayerId;
            this.Direction = Direction;
        }

        public Character()
        {
            this.Direction = new();
        }
    }
}
