// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Entity
    {
        [DataMember(Name = "entity_id")]
        public int EntityId;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;
        [DataMember(Name = "rot_y")]
        public float RotY;
        [DataMember(Name = "entity_type")]
        public string EntityType;
        [DataMember(Name = "created_at")]
        public ulong CreatedAt;

        public Entity(
            int EntityId,
            float PosX,
            float PosY,
            float PosZ,
            float RotY,
            string EntityType,
            ulong CreatedAt
        )
        {
            this.EntityId = EntityId;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
            this.RotY = RotY;
            this.EntityType = EntityType;
            this.CreatedAt = CreatedAt;
        }

        public Entity()
        {
            this.EntityType = "";
        }
    }
}
