// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EntityCharacter
    {
        [DataMember(Name = "entity_id")]
        public int EntityId;
        [DataMember(Name = "character_id")]
        public uint CharacterId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "level")]
        public uint Level;
        [DataMember(Name = "class_name")]
        public string ClassName;
        [DataMember(Name = "race")]
        public uint Race;

        public EntityCharacter(
            int EntityId,
            uint CharacterId,
            string Name,
            uint Level,
            string ClassName,
            uint Race
        )
        {
            this.EntityId = EntityId;
            this.CharacterId = CharacterId;
            this.Name = Name;
            this.Level = Level;
            this.ClassName = ClassName;
            this.Race = Race;
        }

        public EntityCharacter()
        {
            this.Name = "";
            this.ClassName = "";
        }
    }
}
