// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Entity
    {
        [DataMember(Name = "entity_id")]
        public uint EntityId;
        [DataMember(Name = "position")]
        public DbVector2 Position;
        [DataMember(Name = "life")]
        public uint Life;

        public Entity(
            uint EntityId,
            DbVector2 Position,
            uint Life
        )
        {
            this.EntityId = EntityId;
            this.Position = Position;
            this.Life = Life;
        }

        public Entity()
        {
            this.Position = new();
        }
    }
}
