// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Session
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "account_id")]
        public uint AccountId;
        [DataMember(Name = "character_id")]
        public uint CharacterId;
        [DataMember(Name = "last_active")]
        public ulong LastActive;
        [DataMember(Name = "current_zone")]
        public string CurrentZone;

        public Session(
            SpacetimeDB.Identity Identity,
            uint AccountId,
            uint CharacterId,
            ulong LastActive,
            string CurrentZone
        )
        {
            this.Identity = Identity;
            this.AccountId = AccountId;
            this.CharacterId = CharacterId;
            this.LastActive = LastActive;
            this.CurrentZone = CurrentZone;
        }

        public Session()
        {
            this.CurrentZone = "";
        }
    }
}
