// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserNotification
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "message")]
        public string Message;
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;

        public UserNotification(
            SpacetimeDB.Identity Identity,
            string Message,
            ulong Timestamp
        )
        {
            this.Identity = Identity;
            this.Message = Message;
            this.Timestamp = Timestamp;
        }

        public UserNotification()
        {
            this.Message = "";
        }
    }
}
